title: Kangping Hu
position: Undergraduate Student
affiliation: Zhejiang University
email: hukp (at) zju.edu.cn
keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=CInzdd8AAAAJ&hl=en
github_link: https://github.com/HenryHu-H
linkedin: https://www.linkedin.com/in/kangping-henry-hu
avatar: ./assets/img/avatar.png
google_analytics: G-CJYF16EPNW
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
